spring:
  application:
    name: PortalStorageApi  # Service registers under this name
  security:
    username: admin
    password: openpaasta
  servlet:     # spring boot 2.x
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
      location: ${java.io.tmpdir}
management:
  security:
    enabled: false

# HTTP Server
server:
  port: ${PORT:2226}   # HTTP (Tomcat) port

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2221/eureka/
      registry-fetch-interval-seconds: 5
  instance:
    hostname: ${spring.cloud.client.hostname}
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 10

objectStorage:
  swift:
    tenantName: paasta-portal
    username: paasta-portal # YOUR OBJECT STORAGE ACCOUNT
    password: 'PASSWORD' # YOUR OBJECT STORAGE PASSWORD
    authUrl: http://XXX.XXX.XXX.XXX:5000/v2.0/tokens  #YOUR OBJECT STORAGE API URL
    authMethod: keystone
    preferredRegion: Public
    container: portal-container
    user:
      app:
        size:
          mb: 0

paasta:
  portal:
    storage:
      api:
        common:
          countoflastestexception: 10

logging:
  level:
    ROOT: INFO
  file:
    path: classpath:logback-spring.xml
    name: logs/application.log
